### ISSUE TITLE
Inconsistent stack samples

### ISSUE THREAD

**Issue by chrisseaton** [rbspy/rbspy#315] opened 2021-04-15 15:30 UTC
Hello I'm not an expert in `rbspy` so I hope I'm understanding this issue correctly and it is in fact a bug.

```ruby
def foo
  bar
end

def bar
  baz
  bob
end

def baz
  [1, 2, 3].map(&:succ)
end

def bob
  [1, 2, 3]
end

loop do
  foo
end
```

When I profile this program using `rbspy` `0.5.0` with both Ruby 2.7.2 and 3.0.1 I get a flame graph that shows for example `succ` being called from `bob`, as well as from `baz`.

<img width="1562" alt="Screenshot 2021-04-15 at 16 22 16" src="https://user-images.githubusercontent.com/341094/114895038-0de4f300-9e07-11eb-9ace-b1032ef9857e.png">

The raw logs also show it:

```
{
   "trace":[
      {
         "name":"succ [c function]",
         "relative_path":"(unknown)",
         "absolute_path":null,
         "lineno":0
      },
      {
         "name":"map [c function]",
         "relative_path":"(unknown)",
         "absolute_path":null,
         "lineno":0
      },
      {
         "name":"bob",
         "relative_path":"tool/diffprof/rbspy-query.rb",
         "absolute_path":"/Users/chrisseaton/Documents/truffleruby/tool/diffprof/rbspy-query.rb",
         "lineno":16
      },
      {
         "name":"bar",
         "relative_path":"tool/diffprof/rbspy-query.rb",
         "absolute_path":"/Users/chrisseaton/Documents/truffleruby/tool/diffprof/rbspy-query.rb",
         "lineno":8
      },
      {
         "name":"foo",
         "relative_path":"tool/diffprof/rbspy-query.rb",
         "absolute_path":"/Users/chrisseaton/Documents/truffleruby/tool/diffprof/rbspy-query.rb",
         "lineno":3
      },
      {
         "name":"block in <main>",
         "relative_path":"tool/diffprof/rbspy-query.rb",
         "absolute_path":"/Users/chrisseaton/Documents/truffleruby/tool/diffprof/rbspy-query.rb",
         "lineno":20
      },
      {
         "name":"loop [c function]",
         "relative_path":"(unknown)",
         "absolute_path":null,
         "lineno":0
      },
      {
         "name":"<main>",
         "relative_path":"tool/diffprof/rbspy-query.rb",
         "absolute_path":"/Users/chrisseaton/Documents/truffleruby/tool/diffprof/rbspy-query.rb",
         "lineno":18
      }
   ],
   "pid":8126,
   "thread_id":4547739136,
   "time":{
      "secs_since_epoch":1618497446,
      "nanos_since_epoch":257731000
   }
}
```

I don't understand how it's getting this stack trace sample from this program?

As I say I'm not an expert, but is it possible that this stack trace really ends at the call to `bob`, and the two entries on top of that are memory left on the call stack which hasn't been cleared, or the stack pointer is incorrectly sampled?

Possibly unrelated, but there also seem to be incorrect line numbers - it's like each activation always points to the `end` of the method, even if for example it's calling `baz` from `bar`, so not at the end of the method.

Thanks in advance for any help!

**Comment by acj** [comment] 2021-04-17 00:32
Hey, thanks for the good report. I'm able to reproduce this and agree that it's a bug. It's interesting that `succ` is getting marked as a C function -- might be a clue to what's going on.

> is it possible that this stack trace really ends at the call to bob, and the two entries on top of that are memory left on the call stack which hasn't been cleared, or the stack pointer is incorrectly sampled?

That's possible. We don't pause the target process when we're taking the samples, so there are race conditions that can affect the samples. This issue seems very consistent, though, which makes me think there's a logic bug somewhere. I'll look into it.

**Comment by acj** [comment] 2021-04-18 21:28
This seems to be a straightforward race condition that can be fixed. Details are in the linked PR.

**Closed** 2021-04-19 20:51 UTC
Labels: bug
