### ISSUE TITLE
Support 32-bit Ruby on Windows

### ISSUE THREAD

**Issue by ashmaroli** [rbspy/rbspy#172] opened 2018-08-31 13:48 UTC
I downloaded the **three binaries** at this [link](https://ci.appveyor.com/project/jvns/rbspy/build/1.0.14/artifacts) and moved them into my Ruby installation's `bin` dir (because it is already in `%PATH%`)

Then I ran `rbspy record` on a local Ruby script, `test.rb` (The Ruby script basically benchmarks a Rubygem):
```
rbspy record ruby test.rb
```
Instead of exit as expected, the process hangs with following output:
```
Wrote raw data to C:\Users\<username>\.cache\rbspy\records\rbspy-2018-08-31-NAQkINnvBy.raw.gz
Writing formatted output to C:\Users\<username>\.cache\rbspy\records\rbspy-2018-08-31-MfU01PweQl.flamegraph.svg
ERROR: No stack counts found
Error. Causes:
- Couldn't determine Ruby version
- Couldn't create process handle for PID
- failed to find ruby_version symbol

[... partial output from script]
```
Thinking, `rbspy` is getting choked on a *subprocess*, I ran the following:
```
 rbspy record --subprocesses ruby test.rb
```
But that exited immediately with following output:
```
Error. Causes:
- --subprocesses option is not available on windows
```

**Comment by benfred** [comment] 2018-08-31 20:10
@ashmaroli  Thanks for the bug report! I'd like to try to replicate your problem on my own windows box, and I was wondering if I could get some extra info from you. Specifically, what version of ruby are you running? Is your ruby from the [rubyinstaller](https://rubyinstaller.org/downloads/) package or some other source? 

From the error message it looks like it failed to find the ruby_version symbol - which was included in all the ruby versions I tried. If you have a native debugger (like visual studio or [x64dbg](https://x64dbg.com/)) you could also see if this symbol can be resolved in your ruby program.

**Comment by ashmaroli** [comment] 2018-08-31 20:17
@benfred I encountered this issue on Ruby 2.3.1 (32-bit) installed via RubyInstaller. The binaries for `rbspy` have been placed in the same directory as the Ruby executable.

Unfortunately, I do not have native debuggers installed on my system.

**Comment by benfred** [comment] 2018-08-31 22:04
thanks! I've managed to replicate the problem with that info, and it looks like it is an issue with profiling 32-bit ruby builds on windows. The problem with loading the ruby_version symbol was that this symbol is part of the msvcrt-ruby230.dll file , which is a 32 bit dll and wasn't being returned from the get_process_maps calll. I have a fix here https://github.com/benfred/proc-maps/pull/1 after which the ruby_version is correctly loaded up. 

Unfortunately even with this fix, there seems to be another problem with 32 bit (Too much memory requested when copying/). I'm looking into this right now.

fwiw, I just tested the Ruby 2.3.1 64 bit version from ruby installer and rbspy works against that. As a short term workaround until we get this fix in you could switch to the 64 bit ruby build.

**Comment by benfred** [comment] 2018-08-31 22:58
So - I managed to get a version of this that works. The problem was that the rbspy binary we are distributing right now is compiled for the x86_64 toolchain - meaning that pointers and usize variables in ruby_structs are 64 bit where they are only 32 bit in the profiled program. 

To fix this properly I think we will have to build/distribute 32 bit versions of rbspy (like build with the stable-i686-pc-windows-msvc toolchain) as well as the 64 bit versions. I don't see an easy way of shipping a single binary that supports profiling both 64bit and 32bit ruby on windows =(.

Most of the changes to get this going will be in the appveyor config, but we also need to change a bunch more u64 variables in the generated ruby-structs files to usize to get this to compile. Will have a PR for these in a bit

**Comment by benfred** [comment] 2018-08-31 23:37
This PR fixes so that we can build against the i686 toolchain: https://github.com/rbspy/rbspy/pull/173 . With these two PR's it seems like everything works for the 32 bit ruby versions.

**Comment by benfred** [comment] 2018-09-01 00:46
@ashmaroli You can grab a 32 bit version of rbspy here : https://ci.appveyor.com/project/jvns/rbspy/build/1.0.21/job/8ql5u32yhh8675vo/artifacts . I think this should work work for you

**Comment by ashmaroli** [comment] 2018-09-01 04:36
@benfred Thank you very much for looking into this and preparing the patches.
Here's the current situation:

- I now have Ruby 2.3.1 (32-bit) and Ruby 2.4.4 (64-bit) installed side-by side.
- I moved the original rbspy binaries (built for 64bit env) to my Ruby 2.4 bin folder, and ran my test script. It ran with the following output:
```
[... stack output similar to that in the rbspy docs ...] 
(502/1412) of stack traces were sampled late because we couldn't sample at expected rate, results may be inaccurate.
Try sampling at a lower rate with `--rate`.
Dropped 1452/2903 stack traces because of errors. Please consider reporting a GitHub issue -- this isn't normal.
Wrote raw data to C:\Users\<username>\.cache\rbspy\records\rbspy-2018-09-01-V7IKLTtmpB.raw.gz
Writing formatted output to C:\Users\<username>\.cache\rbspy\records\rbspy-2018-09-01-JKzmsdPWFp.flamegraph.svg
Error. Causes:
- Failed to copy memory address 67beacc0
- Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (os error 299)
```
Nevertheless, the generated flamegraph had *some data..* (Will profile with `jekyll` later today to see if the results are conclusive)
- I also downloaded the new binaries built for 32Bit into my Ruby 2.3 directory. But unfortunately, the program exited with a Windows Error windows with message:
```
The program can't start because VCRUNTIME140.dll is missing from your computer..
```
I'm assuming this particular issue to be specific to my system because I have installed and uninstalled numerous Windows programs and updates since the time I had installed Microsoft Visual Studio suite.
---

Once again, thank you and to @jvns for all the work in bringing Windows compatibility to `rbspy`
:clinking_glasses:

**Comment by benfred** [comment] 2018-09-04 21:36
I have a fix here https://github.com/rbspy/rbspy/pull/178 for the ```Dropped 1452/2903 stack traces because of errors. ``` error message. 

What was happening was that the calls to sleep were always sleeping for 15ms, even though we were asking to sleep for much less time. I didn't see this originally on my system because this is a system wide setting, and I had another program running that set this =(.

With that patch we can sample reliably up to 500 times a second or so on windows (the call to sleep can still take up to 1ms longer than asked for).

**Comment by benfred** [comment] 2018-09-04 22:07
The other error message (```Only part of a ReadProcessMemory or WriteProcessMemory request ...```) was caused by the ruby program exitting while we were still profiling it. I have a PR here to handle this more gracefully https://github.com/rbspy/rbspy/pull/179

**Closed** 2018-09-25 17:51 UTC
