### ISSUE TITLE
Errors profiling at high rates (>= 8000/s)

### ISSUE THREAD

**Issue by dougbarth-stripe** [rbspy/rbspy#155] opened 2018-05-21 15:49 UTC
I'm using rbspy to profile a short lived CLI command (runtime of < 200ms). To get more data, I'm cranking up the sampling rate. My very non-scientific testing showed that rbspy start crashing at around 8000/samples/s.

This is is a Ruby command which is used for autocompletion of AWS resources.
```
$ sudo COMP_LINE="sc as" rbspy record --rate 8000 ./sc-complete
Dropping permissions: running Ruby command as user dougbarth
Press Ctrl+C to stop
Dropped 42/83 stack traces because of errors. Please consider reporting a GitHub issue -- this isn't normal.
Wrote raw data to /Users/dougbarth/.cache/rbspy/records/rbspy-2018-05-21-bB7Zuy1l47.raw.gz
Writing formatted output to /Users/dougbarth/.cache/rbspy/records/rbspy-2018-05-21-GEjZy8R4B0.flamegraph.svg
Error. Causes:
- Copy error: stack base and cfp address out of sync. stack base: 10af73fd0, cfp address: 10af73fd0

asg
```

Here's another variant I've seen.
```
$ sudo COMP_LINE="sc as" rbspy record --rate 10000 ./sc-complete
Password:
Dropping permissions: running Ruby command as user dougbarth
Press Ctrl+C to stop
asg
Dropped 33/65 stack traces because of errors. Please consider reporting a GitHub issue -- this isn't normal.
Wrote raw data to /Users/dougbarth/.cache/rbspy/records/rbspy-2018-05-21-MmFDT8nma9.raw.gz
Writing formatted output to /Users/dougbarth/.cache/rbspy/records/rbspy-2018-05-21-TPzJhLuWPE.flamegraph.svg
Error. Causes:
- Failed to copy memory address 1043f5ef8
- Resource temporarily unavailable (os error 35)
```

Version details:
```
OS X 10.13.3
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
```

**Comment by acj** [comment] 2021-05-09 16:51
I can't reproduce this on master with ruby 2.7.3 or 3.0.1 even with process pausing disabled (`--nonblocking`). rbspy has trouble keeping up at such high sampling rates, but it hasn't crashed on me. Closing until someone runs into this again.

**Closed by acj** 2021-05-09 16:51 UTC
