### ISSUE TITLE
Support higher sample rates than 100 times/second

### ISSUE THREAD

**Issue by jvns** [rbspy/rbspy#126] opened 2018-03-22 16:52 UTC
Right now (since rbspy uses process_vm_readv) it takes more than 1ms to do each sample. This means that we can't really support sample rates of more than 100 times/second.

I'm not sure yet why exactly somebody would need to sample at a rate higher than say 100 times/second, but if somebody has a use case I'd be interested to hear it.

**Comment by zetaben** [comment] 2018-03-23 02:49
Hey there,

We do have such a use case but it is very probably on the edge of what constitute a good use case.                                                     
                                                                                
So we develop and maintain an agent that will [dynamically add protection](https://blog.sqreen.io/dynamic-instrumentation-agent-for-ruby/) inside Ruby applications (most often a Rails applications). What it does behind the scenes is replace some methods in specific classes / objects based on a dynamic configuration. The replaced function will usually look into the arguments provided plus some context (say HTTP parameters) and decide if the function should be run or not (also using dynamic heuristics). We also have the ability to change the return value of such the replaced methods or to do other things if they except.

Obviously these security checks add some overhead in the HTTP request cycle. This overhead, we want it to be the smallest possible. Independent timing measurements (that actually change a bit the runtime of the system) are currently showing, in my target application & test transaction, an overhead of less than 10ms distributed unequally in ~ 300 calls.

This overhead, I actually still want to reduce it.

To do this, I would love to get a trace of what is happening in the request and what is taking time and where it is with a submillisecond resolution. Getting a submillisecond sample interval would be amazing but seems far fetched. So I tried running the same transaction in a loop to get more precision in aggregate. It does work, but the trace stops after about 5 minutes with something that looked like an error (would you be interested in a ticket for this?). rbspy still manages to create a flamegraph which actually shows part of my calls but I would need more runtime and/or better sample rate for this to be better resolved.

Does this actually sound sane?

By the way I was quite blown away with ease of use & general quality of rbspy. I actually reused it on part of my problem, on an isolated piece of code, and it helped me do some nice optimizations.
                                                                                
Very big kudos for this tool! :tada:

**Comment by jvns** [comment] 2018-03-23 03:04
@zetaben I'd be very interested in an issue for the error you ran into!

I might have time this week to work on supporting higher sample rates. If I do I'll cc you so you can test it out!

**Comment by zetaben** [comment] 2018-03-27 00:25
Quick note just to let you know that I did not forget about the bug report @jvns.
Since writing this I have been trying on & off to reproduce the bug I encountered, to no avail... Still If I ever manage to redo what I was doing wrong, I'll fill it.
On the plus side, I now get longer running flamegraph so I get a bit more data to work on! I still be very interested by having support for higher sample rate though (lower testing runtime!)

**Comment by jvns** [comment] 2018-03-27 22:00
@zetaben I'm still not sure how to improve performance, but I just merged https://github.com/rbspy/rbspy/pull/129 (and released 0.2.3 which includes it) which makes it more clear how badly the sample rate is affecting rbspy's accuracy on your program. (so if there are only a small number of late stack traces, it won't complain)

**Comment by doudou** [comment] 2019-10-25 17:14
I'm not sure this issue is still really an issue. I'm tracing at 1k/s without any problem, 10% late traces at 2k/s 

For the record, high sample rates are nice for short-lived programs (i.e. optimizing a CLI tool)

**Comment by acj** [comment] 2021-04-19 19:38
I agree that this doesn't seem to be an issue in practice anymore. Closing, but feel free to reopen if you find that it's still a problem.

**Closed by acj** 2021-04-19 19:38 UTC

**Comment by zetaben** [comment] 2021-04-20 08:41
Sorry missed the notifications about this issue. I'm not really doing those kinds of traces anymore. It's all working very well as far as I have been using it! Thanks again for the tool team.
